// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumMediaResponse = { id: string, album_id: string, url: string, mime_type: string, media_kind: string, width: number | null, height: number | null, ordinal: number, caption: string | null, };
