// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumSummary = { id: string, author_id: string, author_display: string | null, author_handle: string | null, name: string, description: string | null, cover_url: string | null, visibility: string, published_at: string, photo_count: number, };
