// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumSummary = { id: string, author_id: string, author_display: string | null, author_handle: string | null, name: string, description: string | null, cover_url: string | null, 
/**
 * Inline base64 WebP data URI of the album cover's 64px icon. Used by
 * BrowseRail album entries and the Albums overview grid to render
 * covers without per-row image fetches.
 */
cover_icon_data: string | null, visibility: string, published_at: string, photo_count: number, };
