// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumMediaResponse } from "./AlbumMediaResponse";

export type AlbumResponse = { id: string, author_id: string, author_display: string | null, author_handle: string | null, name: string, description: string | null, 
/**
 * Implicit cover: the lowest-ordinal media. Null when the album has
 * no media.
 */
cover_media_id: string | null, cover_url: string | null, 
/**
 * Visibility stored on the album row. For categorized albums this
 * is preserved-but-ignored; the category drives access.
 */
visibility: string, 
/**
 * Visibility actually enforced. Equals the category's visibility
 * when categorized, else the album's own visibility.
 */
effective_visibility: string, published_at: string, created_at: string, updated_at: string, media: Array<AlbumMediaResponse>, photo_count: number, category_id: string | null, };
