// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostCategoryRef } from "./PostCategoryRef";

export type ArticleSummary = { id: string, author_id: string, author_display: string | null, author_handle: string | null, title: string, subtitle: string | null, excerpt: string | null, reading_time_minutes: number, cover_media_id: string | null, cover_url: string | null, is_draft: boolean, visibility: string, effective_visibility: string, published_at: string, updated_at: string, reaction_count: number, comment_count: number, category: PostCategoryRef | null, };
