// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostCategoryRef } from "./PostCategoryRef";

export type ArticleResponse = { id: string, author_id: string, author_display: string | null, author_handle: string | null, author_avatar_url: string | null, title: string, subtitle: string | null, body: string, body_html: string, excerpt: string | null, reading_time_minutes: number, cover_media_id: string | null, cover_url: string | null, is_draft: boolean, visibility: string, effective_visibility: string, published_at: string, created_at: string, updated_at: string, reaction_counts: Record<string, number>, viewer_reaction_kinds: Array<string>, comment_count: number, category: PostCategoryRef | null, };
