// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArticlePreview = { title: string, subtitle: string | null, excerpt: string | null, cover_media_id: string | null, cover_url: string | null, reading_time_minutes: number, };
