// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthConfigResponse = { oidc_enabled: boolean, login_url: string | null, account_url: string | null, 
/**
 * The deployment's domain, gating the admin email on the register page.
 * Sourced from the runtime SITE_DOMAIN env so one image serves any site;
 * empty when unset.
 */
site_domain: string, };
