// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthConfigResponse = { oidc_enabled: boolean, login_url: string | null, account_url: string | null, };
