// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkStateEntry } from "./BulkStateEntry";

export type BulkStateResponse = { states: { [key in string]: BulkStateEntry }, };
