// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CategoryResponse = { id: string, name: string, slug: string, ordinal: number, color: string | null, visibility: string, created_by: string | null, 
/**
 * Whether the caller can manage (edit / delete / change membership)
 * this category. Lets the social-frontend show or hide Manage
 * affordances per row without a second permission check.
 */
manageable: boolean, };
