// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateArticleRequest = { title: string, body: string | null, subtitle: string | null, excerpt: string | null, visibility: string | null, category_id: string | null, cover_media_id: string | null, 
/**
 * Defaults to true: composer's first call mints a draft.
 * Set to false to publish directly without a draft round-trip.
 */
is_draft: boolean, };
