// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateInviteRequest = { 
/**
 * Optional name/email hint for the recipient. Surfaces in the admin list
 * and in the splash to help the visitor confirm the invite is for them.
 */
email_hint: string | null, 
/**
 * Lifetime in hours. Capped at `MAX_INVITE_LIFETIME_DAYS`; defaults to one week.
 */
expires_in_hours: bigint | null, };
