// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create payload for `POST /api/articles`. `cover_media_id` is
 * intentionally absent: set the cover via PATCH after uploading media
 * to the new article (the row id doesn't exist yet at create time, so
 * the PATCH path's "media must belong to this article" invariant can't
 * be enforced here).
 */
export type CreateArticleRequest = { title: string, body: string | null, subtitle: string | null, excerpt: string | null, visibility: string | null, category_id: string | null, 
/**
 * Defaults to true: composer's first call mints a draft.
 * Set to false to publish directly without a draft round-trip.
 */
is_draft: boolean, };
