// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurrentInviteResponse = { code: string, email_hint: string | null, expires_at: string, };
