// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostResponse } from "./PostResponse";

export type FeedResponse = { posts: Array<PostResponse>, next_cursor: string | null, };
