// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedQuery = { 
/**
 * Cursor in the form `{published_at_rfc3339}_{post_id}`. Returned in
 * the previous page's `next_cursor`. Omitted on first page.
 */
cursor: string | null, 
/**
 * Page size. Capped server-side.
 */
limit: number | null, 
/**
 * Optional author filter.
 */
author: string | null, 
/**
 * Optional category filter. Slug, not id, for nice URLs.
 * `?category=uncategorized` matches posts with `category_id IS NULL`.
 */
category: string | null, 
/**
 * Search term. Empty/whitespace = no filter. When set, ordering
 * switches to BM25 relevance and pagination collapses to a single page.
 */
q: string | null, };
