// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportJobResponse = { id: string, kind: string, status: string, created_by: string, parent_job_id: string | null, params: unknown, progress: unknown, 
/**
 * Structured per-job log. Shape: `{ entries: [{ts, level, msg, ctx?}],
 * dropped: N }`. The admin UI renders this as a chronological event
 * list so an operator can see exactly where an import went wrong.
 */
log: unknown, error: string | null, last_heartbeat_at: string | null, started_at: string | null, finished_at: string | null, created_at: string, updated_at: string, };
