// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Admin-facing view of an invite. The plaintext `code` is `Some` only on
 * the creation response (where the admin/auto-issuer needs to deliver it
 * out-of-band). Listing and revoke responses leave it `None` because the
 * DB only stores the hash and there is no way to recover the plaintext
 * after issuance.
 */
export type InviteResponse = { id: string, code: string | null, email_hint: string | null, created_by: string, expires_at: string, created_at: string, used_at: string | null, used_by_user_id: string | null, revoked_at: string | null, status: string, };
