// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArticleSummary } from "./ArticleSummary";

export type ListArticlesResponse = { articles: Array<ArticleSummary>, next_cursor: string | null, };
