// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListArticlesQuery = { cursor: string | null, limit: number | null, author: string | null, category: string | null, q: string | null, };
