// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListAlbumsQuery = { cursor: string | null, limit: number | null, author: string | null, 
/**
 * Optional category filter, by slug. `uncategorized` matches albums
 * with `category_id IS NULL`.
 */
category: string | null, };
