// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaReactionStateResponse = { reaction_counts: Record<string, number>, viewer_reaction_kinds: Array<string>, };
