// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaVariantEntry } from "./MediaVariantEntry";

export type MediaVariantsResponse = { variants: Array<MediaVariantEntry>, };
