// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaVariantEntry = { id: string, 
/**
 * Base64 `data:image/webp;base64,...` URI for the requested variant,
 * or `null` if the row has no pre-generated variant (videos, items
 * uploaded before the feature shipped, decode failures during import).
 */
data: string | null, };
