// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inline-variant query for `GET /api/posts/{parent_id}/media-variants`.
 * `variant` selects which derived size to return (`thumbnail` today;
 * reserved for future expansion). `ids` is a comma-separated list of
 * media UUIDs, all of which must belong to the path parent.
 */
export type MediaVariantsQuery = { variant: string, ids: string, };
