// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaCommentResponse = { id: string, media_id: string, user_id: string, author_display: string | null, author_handle: string | null, author_avatar_url: string | null, body: string, body_html: string, created_at: string, updated_at: string, edited_at: string | null, };
