// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberResponse } from "./MemberResponse";

export type MembersListResponse = { members: Array<MemberResponse>, };
