// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchMeProfileRequest = { handle: string | null, display_name: string | null, bio: string | null, pronouns: string | null, };
