// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchMeLocaleRequest = { 
/**
 * One of `crate::profile::locale::SUPPORTED_LOCALES`. Anything else
 * returns 400.
 */
locale: string, };
