// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentResponse } from "./CommentResponse";
import type { PostCategoryRef } from "./PostCategoryRef";
import type { PostMediaResponse } from "./PostMediaResponse";

export type PostResponse = { id: string, author_id: string, author_display: string | null, author_handle: string | null, author_avatar_url: string | null, body: string, body_html: string, 
/**
 * Visibility stored on the post row. For categorized posts this is
 * preserved-but-ignored; the category drives access.
 */
visibility: string, 
/**
 * Visibility actually enforced for this post.
 */
effective_visibility: string, published_at: string, created_at: string, updated_at: string, media: Array<PostMediaResponse>, reaction_counts: Record<string, number>, viewer_reaction_kinds: Array<string>, comment_count: number, category: PostCategoryRef | null, top_comments: Array<CommentResponse>, };
