// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostMediaResponse = { id: string, 
/**
 * Browser-facing URL. Hits `/media/{media_id}` which checks tier
 * visibility before serving from S3.
 */
url: string, mime_type: string, 
/**
 * Coarse kind derived from `mime_type`: `"image"` or `"video"`.
 */
media_kind: string, width: number | null, height: number | null, ordinal: number, caption: string | null, };
