// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact profile shape used by the list endpoint. Drops `bio` and
 * `pronouns` since they aren't shown in the rail or directory grid.
 */
export type ProfileSummary = { user_id: string, handle: string, display_name: string | null, avatar_url: string | null, role: string, };
