// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response shape for public profile reads. Email is intentionally omitted:
 * public profiles are visible to anyone who can reach the page; the
 * recipient's email is not.
 *
 * `follows_you` and `you_follow` are populated for authenticated viewers
 * only; both are `false` for anonymous reads since the relationship has
 * no defined viewer.
 */
export type PublicProfileResponse = { user_id: string, handle: string, display_name: string | null, bio: string | null, pronouns: string | null, avatar_url: string | null, role: string, follower_count: number, following_count: number, follows_you: boolean, you_follow: boolean, };
