// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact "reactions on a post" wire summary. Used by both the post
 * reaction endpoints and (via [`MediaEngagementResponse`]) the per-media
 * lightbox.
 */
export type ReactionStateResponse = { reaction_counts: Record<string, number>, viewer_reaction_kinds: Array<string>, };
