// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateArticleRequest = { title: string | null, subtitle: string | null, body: string | null, excerpt: string | null, visibility: string | null, category_id: string | null, clear_category: boolean, cover_media_id: string | null, clear_cover: boolean, 
/**
 * Publish toggle: passing `false` here flips a draft into a published
 * article (bumps `published_at`, applies the chosen visibility).
 * Going from published to draft is not supported.
 */
is_draft: boolean | null, };
