// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePostRequest = { body: string | null, visibility: string | null, 
/**
 * Assign / move to a different category. Provide a UUID to set; omit
 * to leave alone. Pair with `clear_category=true` to remove a
 * categorization without a sentinel value.
 */
category_id: string | null, 
/**
 * Explicit boolean: set to true to clear the post's category.
 * Omitted = no change, true = clear, false = no change.
 */
clear_category: boolean, };
