// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePostMediaRequest = { 
/**
 * Empty/whitespace clears the caption (NULL); a present value
 * replaces it. Omitted means "leave alone".
 */
caption: string | null, };
