// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCategoryRequest = { name: string | null, slug: string | null, ordinal: number | null, color: string | null, visibility: string | null, };
