// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAlbumRequest = { name: string | null, description: string | null, visibility: string | null, 
/**
 * Explicit cover override. Translated under the hood into a reorder
 * that moves the chosen media to ordinal=0 and shifts the others.
 */
cover_media_id: string | null, category_id: string | null, clear_category: boolean, };
