// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAlbumMediaRequest = { caption: string | null, 
/**
 * Direct ordinal patch. Callers that want a full reorder (cover
 * promotion, drag-to-reorder UI) should use the album-level
 * `cover_media_id` PATCH or compose multiple PATCH calls.
 */
ordinal: number | null, };
