// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureFlags } from "./FeatureFlags";

export type UserResponse = { id: string, email: string, email_verified: boolean, totp_enabled: boolean, mfa_required: boolean, active: boolean, force_password_change: boolean, role: string, 
/**
 * Public handle for the caller. Surfaced here so the social-frontend's
 * header dropdown can deep-link to `/u/{handle}` without an extra
 * fetch.
 */
handle: string | null, avatar_url: string | null, avatar_icon_data: string | null, 
/**
 * Saved UI locale. NULL when the user has never explicitly chosen one;
 * the frontend's i18next browser-language detector fills the gap.
 */
locale: string | null, features: FeatureFlags, };
