// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSummary = { user_id: string, handle: string, display_name: string | null, avatar_url: string | null, avatar_icon_data: string | null, role: string, };
